
baseurl                 = "https://pureone-t.github.io/doc-site/" # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "doc site"
theme                   = "sam"
pygmentsStyle           = "monokai" # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"

[params]
    #dateform            = "Mon Jan 02, 2006"
    dateform            = "2006-01-02 (Mon)"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.ico"
    homepage            = "Top"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "&copy; 2018 pureone-t."

# Metadata
    description         = "doc site by pureone-t."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "posts"
    text = "Posts"

[[params.mainMenu]]
    link = "tags"
    text = "Tag"

[[params.mainMenu]]
    link = "about"
    text = "AboutMe"
